name: Build Windows Mini Floating

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # paksa Node 24
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24   # update versi Node ke 24

      - name: Install Dependencies
        run: npm install

      - name: Build Installer
        run: npm run build

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: mileboard-mini-pro
          path: dist/*.exe
